# Generated by Django 2.2.5 on 2019-09-19 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20190919_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_html',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('user', 'cover', 'message')},
        ),
    ]
